Fix AttributeError: 'Member' object has no attribute 'game' in \findu
Member.game has been replaced by Member.activity, which also works
differently than before. Thanks to Noahkiq for the fix.