Fix `AttributeError: 'NoneType' object has no attribute 'is_default'`
This would happen when a user rejoins a server, they're in the role
cache, but one of the roles they had no longer exists. This is one of
those bugs that you just only stumble upon years down the road (if
you don't test for everything that can happen)