Fix TypeError in on_member_join
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Invite.uses can be None, so check for that case.